combine workflows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,6 +3,12 @@ on:
   push:
     branches:
       - "**"
+  pull_request:
+    paths-ignore:
+      - docs
+      - .devcontainer
+      - examples
+
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -32,3 +38,64 @@ jobs:
     #   with:
     #     version: latest
     #     args: --timeout=5m --config=.golangci.yaml provider
+
+  build_sdks:
+    name: Build SDKs
+    if: github.event_name == 'pull_request'
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        language:
+        - nodejs
+        - python
+        - dotnet
+        - go
+        provider:
+        - aws
+        - gcp
+        - azure
+
+    steps:
+    - name: Checkout Repo
+      uses: actions/checkout@v4
+
+    - name: Setup and build SDK
+      uses: ./.github/actions/build-sdk
+      with:
+        language: ${{ matrix.language }}
+        provider: defang-${{ matrix.provider }}
+
+    - name: Check clean sdks working tree
+      run: |
+        git update-index -q --refresh
+        if ! git diff-index --quiet HEAD -- sdks/; then
+          >&2 echo "error: sdks directory is not clean, aborting!"
+          git status sdks/
+          git diff sdks/
+          exit 1
+        fi
+
+    - name: Build Example
+      run: make example_${{ matrix.provider }}_${{ matrix.language }}
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
+
+    - name: Check clean examples working tree
+      run: |
+        git update-index -q --refresh
+        if ! git diff-index --quiet HEAD -- examples/; then
+            >&2 echo "error: examples directory is not clean, aborting!"
+            git status examples/
+            git diff examples/
+            exit 1
+        fi
+
+    - name: Ensure clean example versions
+      run: |
+        if grep -r '+dirty' examples/; then
+          >&2 echo "error: found +dirty version in examples. Regenerate examples with \`make examples\` and commit the changes."
+          exit 1
+        fi
