fix: format YAML workflow; build images after test/sdks

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,50 +19,50 @@ jobs:
       group: test-${{ github.ref }}
       cancel-in-progress: true
     steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v6
+      - name: Checkout Repo
+        uses: actions/checkout@v6
 
-    - name: Install Go
-      uses: actions/setup-go@v6
-      with:
-        go-version-file: go.mod
-        cache-dependency-path: go.sum
+      - name: Install Go
+        uses: actions/setup-go@v6
+        with:
+          go-version-file: go.mod
+          cache-dependency-path: go.sum
 
-    - name: Install pulumictl
-      run: |
-        gh release download --repo pulumi/pulumictl --pattern 'pulumictl-*-linux-amd64.tar.gz' --dir /tmp
-        tar -xzf /tmp/pulumictl-*-linux-amd64.tar.gz -C /usr/local/bin pulumictl
-      env:
-        GH_TOKEN: ${{ github.token }}
+      - name: Install pulumictl
+        run: |
+          gh release download --repo pulumi/pulumictl --pattern 'pulumictl-*-linux-amd64.tar.gz' --dir /tmp
+          tar -xzf /tmp/pulumictl-*-linux-amd64.tar.gz -C /usr/local/bin pulumictl
+        env:
+          GH_TOKEN: ${{ github.token }}
 
-    - name: Unshallow clone for tags
-      run: git fetch --prune --unshallow --tags
+      - name: Unshallow clone for tags
+        run: git fetch --prune --unshallow --tags
 
-    - run: make provider
+      - run: make provider
 
-    - run: make schema && git diff --exit-code -- provider/cmd/pulumi-resource-defang/schema.json
+      - run: make schema && git diff --exit-code -- provider/cmd/pulumi-resource-defang/schema.json
 
-    - run: make test
+      - run: make test
 
-    - name: golangci-lint
-      uses: golangci/golangci-lint-action@v9
-      with:
-        version: v2.7.2
-        args: --timeout=5m --config=.golangci.yaml ./provider/...
+      - name: golangci-lint
+        uses: golangci/golangci-lint-action@v9
+        with:
+          version: v2.7.2
+          args: --timeout=5m --config=.golangci.yaml ./provider/...
 
   setup_sdk_matrix:
-    name: Set SDK Matrix
+    name: Set up SDK Matrix
     runs-on: ubuntu-latest
     outputs:
       languages: ${{ steps.matrix.outputs.languages }}
     steps:
-    - id: matrix
-      run: |
-        if [ "${{ github.event_name }}" == "pull_request" ]; then
-          echo 'languages=["go"]' >> $GITHUB_OUTPUT
-        else
-          echo 'languages=["nodejs","python","dotnet","go"]' >> $GITHUB_OUTPUT
-        fi
+      - id: matrix
+        run: |
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            echo 'languages=["go"]' >> $GITHUB_OUTPUT
+          else
+            echo 'languages=["nodejs","python","dotnet","go"]' >> $GITHUB_OUTPUT
+          fi
 
   build_sdks:
     name: Build SDKs
@@ -75,34 +75,34 @@ jobs:
       matrix:
         language: ${{ fromJson(needs.setup_sdk_matrix.outputs.languages) }}
         provider:
-        - aws
-        - gcp
-        - azure
+          - aws
+          - gcp
+          - azure
 
     steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v6
+      - name: Checkout Repo
+        uses: actions/checkout@v6
 
-    - name: Setup and build SDK
-      uses: ./.github/actions/build-sdk
-      with:
-        language: ${{ matrix.language }}
-        provider: defang-${{ matrix.provider }}
+      - name: Setup and build SDK
+        uses: ./.github/actions/build-sdk
+        with:
+          language: ${{ matrix.language }}
+          provider: defang-${{ matrix.provider }}
 
-    - name: Check clean sdks working tree
-      run: |
-        git update-index -q --refresh
-        if ! git diff-index --quiet HEAD -- sdks/; then
-          >&2 echo "error: sdks directory is not clean, aborting!"
-          git status sdks/
-          git diff sdks/
-          exit 1
-        fi
+      - name: Check clean sdks working tree
+        run: |
+          git update-index -q --refresh
+          if ! git diff-index --quiet HEAD -- sdks/; then
+            >&2 echo "error: sdks directory is not clean, aborting!"
+            git status sdks/
+            git diff sdks/
+            exit 1
+          fi
 
-    - name: Build Example
-      run: make example_${{ matrix.provider }}_${{ matrix.language }}
-      env:
-        GITHUB_TOKEN: ${{ github.token }}
+      - name: Build Example
+        run: make example_${{ matrix.provider }}_${{ matrix.language }}
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
 
     # - name: Check clean examples working tree
     #   run: |
@@ -124,7 +124,9 @@ jobs:
   build_image:
     name: Build Docker Image
     runs-on: ubuntu-latest
-    # needs: test # temporarily disabled for faster iteration
+    needs:
+      - test
+      - build_sdks
     permissions:
       packages: write
     steps:
